/** @type {import('tailwindcss').Config} */
module.exports = {
  content: [
    "./index.html",
    "./App.tsx",
    "./main.tsx",
    "./pages/**/*.{js,ts,jsx,tsx}",
    "./components/**/*.{js,ts,jsx,tsx}",
    "./imports/**/*.{js,ts,jsx,tsx}",
  ],
  safelist: [
    // Core layout utilities that MUST be included
    'flex',
    'grid',
    'block',
    'inline-block',
    'hidden',
    'fixed',
    'absolute',
    'relative',
    'sticky',
    'inset-0',
    'top-0',
    'top-4',
    'top-8',
    'left-0',
    'left-4',
    'right-4',
    'bottom-6',
    'bottom-8',
    'left-1/2',
    'z-50',
    'w-full',
    'h-full',
    'h-auto',
    'h-screen',
    'min-h-screen',
    'max-w-3xl',
    'max-w-7xl',
    'mx-auto',
    'items-center',
    'justify-center',
    'text-center',
    'object-cover',
    'overflow-hidden',
    'transition-opacity',
    'transition-colors',
    'transition-all',
    'duration-300',
    'shadow-lg',
    'gap-2',
    'gap-8',
    'space-y-4',
    'space-y-8',
    'flex-col',
    'leading-tight',
    'leading-relaxed',
    'animate-bounce',
    '-translate-x-1/2',
    'border-t',
    'border-b',
    'border-border',
    'px-6',
    'px-8',
    'px-10',
    'py-3',
    'py-4',
    'py-5',
    'pt-24',
    'pt-32',
    'pb-8',
    'pb-20',
    'mb-2',
    'mb-4',
    'mb-12',
    'mb-16',
    'mb-24',
    'mb-32',
    'mb-48',
    'mb-64',
    'mt-16',
    'lg:block',
    'lg:hidden',
    'lg:top-8',
    'lg:left-12',
    'lg:right-12',
    'lg:px-12',
    'lg:py-16',
    'lg:pt-32',
    'lg:mb-12',
    'lg:mb-16',
    'lg:mb-32',
    'lg:mb-48',
    'lg:text-4xl',
    'lg:text-6xl',
    'md:grid-cols-2',
    'md:grid-cols-3',
    'md:text-left',
    'md:text-2xl',
    'md:text-8xl',
    'lg:grid-cols-2',
    'lg:gap-12',
    'lg:gap-16',
  ],
  theme: {
    extend: {
      colors: {
        charcoal: '#525557',
        ivory: '#EEEDE1',
        blue: '#669CC4',
        background: '#EEEDE1',
        foreground: '#525557',
        primary: {
          DEFAULT: '#669CC4',
          foreground: '#EEEDE1',
        },
        muted: {
          DEFAULT: '#f5f4ed',
          foreground: '#6a6b6d',
        },
        border: '#52555726',
        bone: '#EEEDE1',
      },
      fontFamily: {
        sans: ['Cormorant Garamond', 'ui-serif', 'Georgia', 'serif'],
        mono: ['Space Mono', 'ui-monospace', 'monospace'],
      },
      spacing: {
        'section': '128px',
        'section-mobile': '80px',
      },
      borderRadius: {
        sm: '2px',
        md: '4px',
        lg: '8px',
      },
    },
  },
  plugins: [],
}
